# Generated by Django 2.0.5 on 2018-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Event_Start', models.DateTimeField()),
                ('Event_End', models.DateTimeField()),
                ('Body', models.TextField()),
            ],
        ),
    ]
