# Generated by Django 2.0.6 on 2018-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='const',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Constitution_Title', models.CharField(max_length=150)),
                ('Constitution_Body', models.TextField()),
            ],
        ),
    ]
