# Generated by Django 2.0.6 on 2018-06-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='constitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Body', models.TextField()),
            ],
        ),
    ]
